### ISSUE TITLE
Unable to login with google in mySMS

### ISSUE THREAD

**Issue by Kramerbaf** [saenzramiro/rambox#629]
I'm unable to log in with Google in the mySMS service.
I can still log in with my phone number but when I restart my computer, I need to type my number + password again.

### Steps to reproduce

1. Add mySMS Service
2. Clic "Log In with Google" (I'm using French, so : "S'identifier avec Google")
3. New tab opens in Chrome
4. Nothing :(

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Windows 10 64bit

(Still <3 Rambox)

**Comment by JonathanDaSilva** [comment]
Hi.

You can't login with your google account, when you had the service you can see «You have to use this service by signing in with your mobile number.». This is a know issue.

#173 This has already been reported too, the issue was closed but I'm still facing the same problem, we have to wait for the next release ?

In the meantime you can use a «_Custom Service» this solve this problem but you will still have to login with your number.

**Comment by saenzramiro** [comment]
Like @JonathanDaSilva said, for now you have to login with your number.

Logging in with any OAuth SSO service that shows a popup instead of redirecting the page is a problem that we need to solve. In this case, mySMS opens a popup, but then is not passing the session to the web app.

**Comment by JonathanDaSilva** [comment]
@saenzramiro did #173 is release in 0.5.3 ? Because I'm still facing this issue

**Comment by saenzramiro** [comment]
It was fixed in 0.4.3. Try by removing the service and add it again. Remember to log in with your phone number.

**Comment by SimJoSt** [comment]
> It was fixed in 0.4.3.

Did you mean `0.5.3`?

**Comment by saenzramiro** [comment]
No sorry, 0.5.2. You can see the milestone at the left side.

**Comment by JonathanDaSilva** [comment]
@saenzramiro Sorry for the late response. I have had already tried that in 0.5.3 and I have retry today this is not fixed. 

I had the service, I connect with my number, close rambox with the tray icon, relaunch it and he ask again my number and password.

I'm currently using it as a custom services because of that (I haven't this problem in custom services).

**Comment by saenzramiro** [comment]
@JonathanDaSilva Well, we can reopen #173, but before tell me what URL you are using in Custom Service.

**Comment by JonathanDaSilva** [comment]
@saenzramiro "https://app.mysms.com/"

**Comment by saenzramiro** [comment]
Ok, I will take a look.

**Comment by calexicoz** [comment]
Regarding the Google Auth issue, would this be the problem:
https://github.com/electron/electron/issues/8100

**Comment by saenzramiro** [comment]
Right. =/

**Comment by dtiroc** [comment]
I have this same problem.  Can't sign in w Google on Google browser.  But, can sign in w Google in Iexplorer,
